"""empty message

Revision ID: 482f2795c0cd
Revises: 598bebaab14d
Create Date: 2023-04-21 20:48:29.261851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f2795c0cd'
down_revision = '598bebaab14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
