"""empty message

Revision ID: 82ec3300aa65
Revises: df147d818907
Create Date: 2023-05-09 19:21:10.557291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ec3300aa65'
down_revision = 'df147d818907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_planets_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_vehicles_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planets_id')
        batch_op.drop_column('vehicles_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_vehicles_id_fkey', 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key('favorites_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorites_planets_id_fkey', 'planets', ['planets_id'], ['id'])

    # ### end Alembic commands ###
